---
title: "Bandeja de Entrada"
date: ""
output:
  html_document: 
    theme: readable
---

**Tienes un correo sin leer:**

*Re*: Edu

*Asunto*: ¡¡Se ha cometido un crimen!!

*Cuerpo del mensaje*:

Queridos Guille y Laura,

¡No os lo vais a creer! 

Resulta que esta mañana hemos llegado Julián y yo a su despacho, como hacemos muchos días cuando, para nuestra sorpresa, ¡alguien había forzado la puerta!

Algún desalmado ha destrozado todo el despacho, ha puesto todo patas arriba y abierto todos los cajones. Julián está paranoico, piensa que le quieren robar su investigación o intoxicarle con Coronavirus. 

En cualquier caso, lo que más le ha dolido es... ¡¡que han roto el retrato que tenía enmarcado junto con Rabinowitz!!

Julián piensa mal de mucha gente, pero no está seguro de quién puede haber sido, ¡y no podemos acusar a alguien sin pruebas!

Afortunadamente, creo tenemos una pista. Al parecer, el incursor portaba consigo un ejemplar del Diario *Público*, del que se ha desprendido el recorte de un artículo que puede que nos lleve a él.

Yo llevo un tiempo dándole vueltas y la verdad es que soy incapaz de sacar nada en claro, a ver si vosotros sois capaces de resolverlo...

Os adjunto una copia en PDF del recorte del periódico.

Un abrazo,

Edu

Archivo adjunto: [articulo.pdf](articulo.pdf)

[Volver a hablar con el ordenador de Guille](ordenador2.html)

