---
title: "Bandeja de Entrada"
date: ""
output:
  html_document: 
    theme: readable
---

**Tienes un correo sin leer:**

*Re*: Edu

*Asunto*: Arrieta, te tenemos

*Cuerpo del mensaje*: 

Julián dice que ya se lo esperaba, que no podía ser otro. Pues esta vez hay que reconocer que cuando tiene razón, tiene razón.

Hemos ido al despacho de Arrieta y les hemos pillado con las manos en la masa... Parece que todo ha sido una trama obscura dirigida por el SuperCalvo y él. Según han confesado los malandrines, todo el sector "comunista" del departamento está conspirando en contra de él *y de todos sus allegados*. 

Es probable que, dado que Laura hizo el TFG con Julián y éste la tenía en gran estima, hayan intentado ir a fastidiarla a ella primero, usando su brazo toledano, representado por los hermanos Díaz. En cualquier caso, Arrieta y SC afirman no saber nada de eso...

De todas maneras me he acercado a investigar a los despachos de los hermanos Díaz, y no he encontrado nada sospechoso, aunque me ha llamado la atención que ahora están investigando unos problemas sobre autómatas celulares. En una de sus pizarras he encontrado unos diagramas interesantes al respecto, por si les queréis echar un vistazo...

Espero que resolváis pronto el problema.

Besos,

Edu

Imagen adjunta: [pizarra.jpg](pizarra.jpg)
