---
title: "The cocycle approach to algebraic topology"
author: "Guillermo Gallego"
date: "June 12, 2020"
output:
  html_document: 
    toc: true
    toc_float: true
    theme: readable
    includes: 
     in_header: ../headers.html
  pdf_document: 
     includes:
       in_header: ../headers.tex
---

Well, it's been more than a month now. My original purpose was to post a new entry every week but this has certainly been disturbed by my work on my Teacher's Training Master's Thesis (more on this another day, maybe in Spanish). Anyway, here we are again. This is going to be a long one, so prepare yourself.

If you are a graduate student or a last-year undergraduate interested in the fields of geometry and topology, it is very likely that you have taken a first course on Algebraic Topology. Most of these introductory courses tend to cover the topic of covering spaces and their relation with the fundamental group. The main result of this theory is the classification of regular covering spaces also adressed sometimes as the "Galois theory" of covering spaces. This result relies on a more fundamental fact that is the monodromy representation. 
If you have taken this kind of course, probably you had to study some proofs that were rather technical and boring, regarding lifting of paths, of homotopies, etc. Moreover, very likely you have gone through the hell of reading and understanding the proof of the very useful Seifert-Van Kampen theorem.

But what if I told you that all those efforts have been in vain? What if I told you that there is a much more simpler way of dealing with these topics?

Welcome to the *cocycle approach to algebraic topology*.

**[Contar algo más de lo que se va a hacer]**
**[Mencionar el monodromy theorem]**

**Theorem**. Let $G$ be a group and $X$ a topological space admitting a universal covering space. The set of isomorphism classes of $G$-covering spaces of $X$ is in one-to-one correspondence with the set of conjugation classes of $G$-representations of the fundamental group of $X$

$$
\mathrm{Hom}(\pi(X),G)/G.
$$

## Cocycles and covering spaces
The key for the simplicity of the cocycle approach is to define $G$-coverings in a (maybe unexpected) way that we could think as (almost) purely algebraic.

Let $X$ be a topological space and $G$ a group. Moreover, choose $\mathfrak{U}$ any open cover of $X$.

**Definition 1**. A *$\mathfrak{U}$-based $G$-covering space of $X$* consists of a locally constant map $g_{UV}: U\cap V \rightarrow G$ for every $U,V \in \mathfrak{U}$ such that $U\cap V \neq \varnothing$ satisfying the *cocycle condition*, that is, if $U \cap V \cap W \neq \varnothing$, then, for every $x\in U \cap V \cap W$,

$$
g_{UV}(x) g_{VW}(x) = g_{UW} (x).
$$

You should not be impressed by this definition if you have read the previous entries of this blog **[CITAR]**. If you consider the sheaf $\underline{G}$ of locally constant maps from $X$ to $G$ (or equivalently, if you endow $G$ with the discrete topology and consider the sheaf of continuous maps from $X$ to $G$) then we just defined a Čech 1-cocycle on $\mathfrak{U}$ with coefficients in $\underline{G}$. The relation between cocycles and covering spaces is a particular case of the relation between cocycles and torsors. To be consistent with the notation of the previous entries, we will denote the set of $\mathfrak{U}$-based $G$-coverings as $Z^1(\mathfrak{U},\underline{G})$.

## The monodromy representation
Given a topological space $X$, an open cover $\mathfrak{U}$ and a $\mathfrak{U}$-based $G$-covering, we can associate to it a representation of the fundamental group, called the *monodromy representations*. 

For those absent-minded let me recall that if we fix a point $x_0\in X$, the fundamental group of $X$ at $x_0$, denoted by $\pi_1(X,x_0)$ is formed by the homotopy classes of loops based at $x_0$, with the product given by path concatenation. By a *representation* the fundamental group on $G$ we mean a group homomorphism $\pi_1(X,x_0) \rightarrow G$.

To any $\mathfrak{U}$-based $G$ covering $g=(g_{UV})_{U,V \in \mathfrak{U}}$, we can associate its monodromy representation

$$
f_g: \pi_1(X,x_0) \longrightarrow G
$$

in the following way. First, consider a loop based at $x_0$, that is, a continuous map $\sigma:[0,1] \rightarrow X$ with $\sigma(0)=\sigma(1)=x_0$. Now we are going to need an easy technical result, which you may know from your algebraic topology course (if you took one): the [Lebesgue number lemma](http://en.wikipedia.org/wiki/Lebesgue%27s_number_lemma).

**Lemma 2**. Given a compact metric space $(X,d)$ and an open cover of $X$, there exists some number $\delta >0$ such that every subset of $X$ contained in some ball of radius $\delta$ is contained in some member of the cover. 

(You can look in the [Wikipedia page](http://en.wikipedia.org/wiki/Lebesgue%27s_number_lemma) for a proof).

The way that this lemma is going to be useful for us is that it allows us to take a partition $t_0=0<t_1<t_2<...<t_n=1$ of the interval $[0,1]$ in such a way that, for every $i=1,...,n$ there exists some $U_i \in \mathfrak{U}$ such that $\sigma( [t_{i-1},t_{i}] ) \subset U_i$. Now, if we call $x_i=\sigma(t_i)$ and $g_{ij}=g_{U_i U_j}$, we can define

$$
f_g([\sigma]) = g_{12}(x_1) g_{23}(x_2) ... g_{n1}(x_n).
$$

In order to see that this is well defined we have to check that:

1. It does not depend on the choice of the "Lebesgue partition" $t_0<t_1<t_2<...<t_n$ and of the "Lebesgue cover" $U_1,...,U_n$.
   
2. It does not depend on the choice of $\sigma$ inside its homotopy class $[\sigma]$.

To check 1 it suffices to show that the definition is invariant by refinement, and, by induction, we can restrict ourselves to the case of adding one point. Thus, choose any point $t_{i'} \in (t_{i-1},t_i)$ and an open set $U_{i'}$ such that $\sigma([t_{i-1},t_{i'}]) \subset U_{i'}$ and $\sigma([t_{i'},t_{i}]) \subset U_i$. By the cocycle condition we have that

$$
 g_{i-1,i'}(t_{i-1}) g_{i',i}(t_{i-1})=g_{i-1,i}(t_{i-1}). 
$$

In order to check 2 consider two homotopic loops $\sigma$ and $\eta$. Since they are homotopic, there exists some continuous map $F:[0,1]\times [0,1] \rightarrow X$ with $F(0,t)=\sigma(t)$, $F(1,t)=\eta(t)$ and $F(s,0)=F(s,1)=x_0$, for every $(s,t)\in [0,1]\times [0,1]$. Now, we may apply again the Lebesgue number lemma to obtain partitions $s_0=0 <s_1 <...<s_m=1$ and $t_0=0 <t_1 <...<t_m=1$ in such a way that, for every $i=1,...,m$ and $j=1,...,n$ there exists some $U_{ij} \in \mathfrak{U}$ such that 

$$
F([s_{i-1},s_i] \times [t_{i-1},t_i]) \subset U_{ij}.
$$

Moreover, since $F(s,0)=x_0$ for every $s \in [0,1]$, we can choose all the $U_{i1}$ to be equal to some $U_{0}$.

Consider now the map $\gamma:[0,1] \rightarrow G$ that maps any $s \in [s_{i-1},s_i]$ to the element

$$
\gamma(s)= f_g(F(s,-)) = g_{U_{0} U_{i2}}(F(s,t_1)) g_{U_{i2} U_{i3}}(F(s,t_2)) ... g_{U_{in} U_{0}}(F(s,t_n)).
$$

This is well defined since

$$
g_{U_{ij}U_{i (j+1)}} (F(s_i,t_i)) = g_{U_{ij} U_{(i+1) j}} g_{U_{(i+1)j} U_{(i+1) (j+1)}} g_{U_{(i+1) (j+1)}U_{i (j+1)}} (F(s_i,t_i)),
$$

so the definition of $\gamma(s_i)$ does not vary if we regard $s_i$ as an element of the $U_{ij}$ or of the $U_{(i+1) j}$.

Finally, remember that the $g$ functions are locally constant, so $\gamma:[0,1]\rightarrow G$ is a locally constant map. Since $[0,1]$ is connected, $\gamma$ is constant. Therefore,

$$
f_g(\sigma) = \gamma(0) = \gamma(1) = f_g(\eta).
$$

To sum up, we have defined the *monodromy map*

$$
Z^1(\mathfrak{U},\underline{G}) \longrightarrow \mathrm{Hom}(\pi_1(X,x_0), G),
$$

that assigns every $G$-covering $g$ to its monodromy representation $f_g$.

## The Betti groupoid
Consider the *conjugation action* of $G$ on the set $\mathrm{Hom}(\pi_1(X,x_0),G)$, that is, given an element $g \in G$, we can compose any $f:\pi_1(X,x_0) \rightarrow G$ with the inner automorphism defined by $g$ to obtain

$$
(g\cdot f)([\sigma]) = g f([\sigma]) g^{-1}.
$$

If you recall the notion of the *action groupoid* from my previous post **[CITAR]**, we can consider the one associated to this action 

$$
[\mathrm{Hom}(\pi_1(X,x_0),G), G].
$$

This is called the *Betti groupoid*. The set of isomorphism classes of this groupoid 

$$
\mathrm{Hom}(\pi_1(X,x_0),G)/ G
$$
 
is called the *Betti moduli set*. The reason why the name of Betti appears here is because, if $G$ is abelian then the conjugation action of $G$ is trivial and the the Betti groupoid / moduli set is simply the group

$$
\mathrm{Hom}(H_1(X),G),
$$

where $H_1(X)$ is the first (singular) homology group of $X$ which is well known to be the abelianization of $\pi_1(X,x_0)$. 

**Definition 3**. Let $g$ and $g'$ be two $\mathfrak{U}$-based $G$-covering spaces of some topological space $X$. An isomorphism $h$ between $g$ and $g'$ is a collection of locally constant maps $h_U:U \rightarrow G$ for every $U\in \mathfrak{U}$ such that 

$$
g'_{UV} = h_U g_{UV} h_V^{-1}.
$$

If you read my previous posts you might recall that any collection $h=(h_U)_{U\in \mathfrak{U}}$ of maps of this kind is called a ($0$-)cochain, and we denoted the set of cochains as $C^0(\mathfrak{U},\underline{G})$. This set acts on the set of $G$-coverings $Z^1(\mathfrak{U},\underline{G})$ like as

$$
(h\cdot g)_{UV} = h_U g_{UV} h_V^{-1}.
$$

and the category of ($\mathfrak{U}$-based) $G$-coverings is precisely the action groupoid 
$$
(\mathfrak{U}\text{-based) } G \text{-coverings} = [Z^1(\mathfrak{U},\underline{G}),C^0(\mathfrak{U},\underline{G})].
$$

Notice now that

$$
f_{h\cdot g} ([\sigma]) = h_1(x_1) g_{12}(x_1) h_2(x_1)^{-1} h_2(x_2) g_{23}(x_2)... g_{n1}(x_n) h_1(x_n).
$$

But, since the $h_i$ are locally constant on the $U_i$, if we denote $h=h_1(x_0)$, we have,

$$
f_{h\cdot g} ([\sigma]) = h f_{g}([\sigma]) h^{-1}.
$$

Therefore any $G$-covering isomorphism induces a conjugation isomorphism on the Betti groupoid. On the other hand, for any $h \in G$ we can define the $G$-covering isomorphism $(h\cdot g)_{UV}= h g_{UV} h^{-1}$.

In conclusion, the monodromy map defines in fact a fully faithful functor from the category of $G$-coverings to the Betti groupoid:

$$
[Z^1(\mathfrak{U},\underline{G}),C^0(\mathfrak{U},\underline{G})] \longrightarrow[\mathrm{Hom}(\pi_1(X,x_0),G), G].
$$

In the next section we are going to see when this functor is in fact an equivalence of categories (that is, when is it essentially surjective).

## Recovering the covering
A natural question to ask now is if, given a representation of the fundamental group $\pi_1(X,x_0) \rightarrow G$, it is the monodromy representation of some $G$-covering, based in some open cover $\mathfrak{U}$.

The answer is in general no.

However, a $G$-covering can be recovered given some "good" conditions on the topological space $X$. First, we are going to ask that $X$ is *path-connected*. This is not a very strong assumption, since we could restrict ourselves to the study of the path components. The strong assumptions are the local ones: we are going to ask $X$ to be *locally path-connected* and *semilocally simply-connected*. This amounts to say that any open cover of $X$ can be refined to a cover $\mathfrak{U}$ that satisfies the following properties:

+ (P1) Every $U\in \mathfrak{U}$ is path-connected.

+ (P2) Every loop $\sigma$ in any $U\in \mathfrak{U}$ is nullhomotopic *as a loop on $X$*.

Notice that being semilocally simply-connected is slightly weaker that being locally simply-connected (this would mean that every path $\sigma$ on any $U$ is nullhomotopic *on $U$*). A common example of a space which is semilocally simply-connected but not locally simply-connected is the [Hawaiian earring space](http://en.wikipedia.org/wiki/Hawaiian_earring).

Maybe you know these conditions from your Algebraic Topology course, since they are the sufficient and necessary conditions for the existence of a *universal covering space*. We will come to that later.

Now, under these assumptions on $X$, given a homomorphism $f:\pi_1(X,x_0) \rightarrow G$ we can consider an open cover $\mathfrak{U}$ satisfying the conditions above, and we are going to define a $\mathfrak{U}$-based $G$-covering yielding $f$ as its monodromy representation.

First we can use the axiom of choice to choose a point $x_U$ in every $U\in \mathfrak{U}$ and a path $\gamma_U$ joining $x_0$ with $x_U$. Moreover, we clearly can make this choice in a way that, if $x_0 \in U$, then $x_U=x_0$ and $\gamma_U$ is the constant path at $x_0$.

Consider now two open sets $U,V \in \mathfrak{U}$ such that $U\cap V \neq \varnothing$ and a point $x\in U\cap V$. Choose a path $\alpha_U$ joining $x_U$ and $x$ and whose image is completely contained on $U$ and another path $\alpha_V$ joining $x$ and $x_V$ whose image is completely contained on $V$. We can then define the path

$$
\gamma_U * \alpha_U * \alpha_V * \gamma^{-1}_V,
$$

where $*$ stands for the concatenation of paths and $\gamma^{-1}_V$ denotes the path $\gamma_V$ transversed backwards. This path is a loop based on $x_0$ and we can define

$$
g_{UV} (x) = f([\gamma_U * \alpha_U * \alpha_V * \gamma^{-1}_V]).
$$

Note that this definition does not depend on the choice of $\alpha_U$ and $\alpha_V$ since any other $\alpha'_U$ or $\alpha'_V$ will be homotopic to $\alpha_U$ and $\alpha_V$, respectively, as paths on $X$, by the second condition on the open cover.

Let us check now that this is indeed a cocycle. Consider

$$
g_{UV} (x) = f([\gamma_U * \alpha_U * \alpha_V * \gamma^{-1}_V]),
$$

$$
g_{VW} (x) = f([\gamma_V * \beta_V * \beta_W * \gamma^{-1}_W]),
$$

and

$$
g_{UW} (x) = f([\gamma_U * \delta_U * \delta_W * \gamma^{-1}_W]).
$$

Now, $\gamma^{-1}_V * \gamma_V$ is the constant path at $x_V$, so

$$
g_{UV} g_{VW} (x) = f([\gamma_U * \alpha_U * \alpha_V * \beta_V * \beta_W * \gamma^{-1}_W]).
$$

Note that $\alpha_V * \beta_V$ is a loop based on $x$ whose image is contained on $V$, so it is nullhomotopic. Moreover, $\alpha_U$ and $\delta_U$ are paths contained on $U$ joining $x_U$ and $x$, so they are homotopic, and the same goes for $\beta_W$ and $\delta_W$. Therefore, we have

$$
g_{UV} g_{VW} (x) = f([\gamma_U * \delta_U *  \delta_W * \gamma^{-1}_W])=g_{UW}(x).
$$

Finally, we have to check that the monodromy representation $f_g$ is equal to $f$. Consider any loop $\sigma$ based at $x_0$ and recall that we defined the monodromy representation as

$$
f_g([\sigma]) = g_{12}(x_1) g_{23}(x_2) ... g_{n1}(x_n)
$$

for certain $x_1,...,x_n$ given by the Lebesgue number lemma. Now, we can choose paths $\alpha_i$ joining $x_{U_i}$ and $x_i$ contained on $U_i$ and $\beta_i$ joining $x_i$ with $x_{U_{i+1}}$ contained on $U_{i+1}$, so

$$
g_{i (i+1)} (x_i) = f([\gamma_{U_i} * \alpha_i * \beta_i * \gamma_{U_{i+1}}^{-1}]). 
$$

Therefore,

$$
f_g([\sigma]) = f([\gamma_{U_1} * \alpha_1 * \beta_1 * \alpha_2 * \beta_2 * \cdots * \alpha_n * \beta_n * \gamma_{U_1}]).
$$

However, $x_0 \in U_1$, so $x_0=x_n=x_{U_1}$ and $\gamma_{U_1}=\beta_n$ is the constant path at $x_0$ so

$$
f_g([\sigma]) = f([\alpha_1 * \beta_1 * \alpha_2 * \beta_2 * \cdots * \alpha_n]).
$$

Finally, $\alpha_1$ is contained in $U_1$ and joins $x_0$ with $x_1$ and $\beta_i * \alpha_{i+1}$ is contained in $U_{i+1}$ and joins $x_i$ with $x_{i+1}$. Therefore this whole path is homotopic to $\sigma$, so

$$
f_g([\sigma])=f([\sigma]).
$$

In conclusion, we have shown that if we choose an open cover $\mathfrak{U}$ with the conditions P1 and P2 stated above, the monodromy map gives a bijection

$$
Z^1(\mathfrak{U},\underline{G}) \longrightarrow \mathrm{Hom}(\pi_1(X,x_0),G).
$$

From the point of view of action groupoids, we get an equivalence of categories

$$
[Z^1(\mathfrak{U},\underline{G}), C^0(\mathfrak{U},\underline{G})] \longrightarrow [\mathrm{Hom}(\pi_1(X,x_0),G), G].
$$

This is our version of the **monodromy theorem**.

Recall from my previous post **[CITAR]** that the moduli set of the action groupoid $[Z^1(\mathfrak{U},\underline{G}), C^0(\mathfrak{U},\underline{G})]$ is the (first) Čech cohomology set of $\mathfrak{U}$ with coefficients on $\underline{G}$, denoted by $H^1(\mathfrak{U},\underline{G})$. We have shown that this cohomology set is in bijection with the Betti moduli set

$$
H^1(\mathfrak{U},\underline{G}) \longrightarrow \mathrm{Hom}(\pi_1(X,x_0),G)/ G.
$$

## Applications of the monodromy theorem

### The Seifert-Van Kampen theorem

**[Contar algo, mencionar a Grothendieck]**


**Theorem**. Let $X$ be a path-connected, locally path-connected and semilocally simply-connected. Let $U,V \subset X$ be open sets with $X=U\cup V$ such that $U$, $V$ and $U\cap V$ are path-connected, locally path-connected and semilocally simply-connected. Take $x_0 \in U \cap V$. If we consider the diagram given by inclusions


$$
    \begin{CD}
      U \cap V @> i_{U} >> U \\
      @VV i_{V} V   @VV j_{U} V \\
      V @> j_{V} >> X,
    \end{CD}
    $$

the induced diagram on the fundamental groups

$$
    \begin{CD}
      \pi_1(U \cap V,x_0) @> i_{U,*} >> \pi_1(U,x_0) \\
      @VV i_{V,*} V   @VV j_{U,*} V \\
      \pi_1(V,x_0) @> j_{V,*} >> \pi_1(X,x_0)
    \end{CD}
    $$

is a [pushout diagram](http://en.wikipedia.org/wiki/Pushout_(category_theory)).

In order to prove this theorem we have to show that, given any other group $G$ and homomorphisms $h_U: \pi_1(U,x_0) \rightarrow G$ and $h_V: \pi_1(V,x_0) \rightarrow G$ making the following diagram commute

$$
    \begin{CD}
      \pi_1(U \cap V,x_0) @> i_{U,*} >> \pi_1(U,x_0) \\
      @VV i_{V,*} V   @VV h_{U} V \\
      \pi_1(V,x_0) @> h_{V} >> G,
    \end{CD}
    $$

there exists a unique $h:\pi_1(X,x_0) \rightarrow G$ such that $h_i=h \circ j_{i,*}$, $i=U,V$.

Now, given the conditions on $U$, $V$, $U\cap V$ and $X$, we can find an open cover $\mathfrak{U}$ of $X$ such that it and its restrictions $U\cap \mathfrak{U}$, $V \cap \mathfrak{U}$ and $U\cap V \cap \mathfrak{U}$ satisfy the properties P1 and P2. We can then identify $\mathrm{Hom}(\pi_1(X,x_0),G)$ with $Z^1(\mathfrak{U},\underline{G})$ and similarly for $U$, $V$ and $U \cap V$. Moreover, it is easy to check that the natural map $Z^1(\mathfrak{U},\underline{G}) \rightarrow Z^1(U\cap \mathfrak{U}, \underline{G})$ given by restriction corresponds to a map $\mathrm{Hom}(\pi_1(X,x_0),G) \rightarrow \mathrm{Hom}(\pi_1(U,x_0),G)$ sending any $h: \pi_1(X,x_0) \rightarrow G$ to $h_U=h\circ j_{U,*}: \pi_1(U,x_0) \rightarrow G$ (same goes for $V$ and $h_V$).

Therefore, we just need to show that if $g_U \in Z^1(U\cap \mathfrak{U}, \underline{G})$ and $g_V \in Z^1(V \cap \mathfrak{U}, \underline{G})$ are two cocycles that coincide in the restriction $Z^1(U\cap V \cap \mathfrak{U}, \underline{G})$, then there exists some cocycle $g \in Z^1(\mathfrak{U}, \underline{G})$ yielding $g_U$ and $g_V$ after restricting to $U$ and $V$ respectively.

The reason behind this is the sheaf condition. Explicitly, given $U_1, U_2 \in \mathfrak{U}$, with $U_1 \cap U_2 \neq \varnothing$ and $x \in U_1 \cap U_2 \cap U \cap V$, if

$$
g_{U,12}(x) = g_{V,12}(x),
$$

then, since they are locally constant, $g_{U,12}=g_{V,12}$ in all the path-component of $U_1 \cap U_2$ containing $x$. Therefore, for every $x\in U_1 \cap U_2$, we can define $g_{12}(x)$ to be $g_{U,12}(x)$ if $x\in U$ and $g_{V,12}(x)$ if $x\in V$. Putting all these together we obtain the cocycle $g\in Z^1(\mathfrak{U},\underline{G})$ we were looking for.

### The topological properties of $G$-coverings
In a similar way as what we did in my previous post **[CITAR]** to relate torsors with cocycles, to any $G$-covering $g$ we can associate a topological space $X_g$ mapping to $X$. We do this in the following way. 

Consider $g$ a $\mathfrak{U}$-based $G$-covering and define the set

$$
X_g = \coprod_{U \in \mathfrak{U}} U \times G / \sim,
$$

with the equivalence relation $\sim$ given as

$$
(x,h) \sim (x,h')
$$

if there exist $U,V \in \mathfrak{U}$ such that $x\in U\cap V$ and $h'=g_{UV}(x) h$. If we take the discrete topology on $G$, we can endow $X_g$ with the quotient topology and we get a canonical continuous surjective map $p:X_g \rightarrow X$ sending every $[(x,g)]$ to $x$.

Some topological properties of the space $X_g$ are determined by the monodromy representation $f_g:\pi_1(X,x_0) \rightarrow G$. If $X$ is path-connected then:

+ the space $X_g$ is path-connected if and only if $f_g$ is surjective.

+ every path component of $X_g$ is simply connected if and only if $f_g$ is injective.

Let us see why these properties are true. First, if $X_g$ is path-connected, that means that for any $h \in G$ there is some path $\gamma$ joining $[(x_0,1_G)]$ with $[(x_0,h)]$. This path must pass through some $U_0 \times \{h_0=1_G\}, U_1 \times \{h_1\}, ..., U_n \times \{h_n=h\}$ in such a way that $h_i(x_i)=g_{i-1,i}(x_i) h_{i-1}(x_i)$.  Now, $p\circ \gamma$ is a loop based in $x_0$ and 

$$
f_g([p\circ \gamma])=g_{12}(x_1)...g_{n1}(x_n)=h.
$$

On the other hand, if $h=f_g([\sigma])$ there are some $U_0,...,U_n$ and $x_0,...,x_n$ with 

$$
h=g_{12}(x_1)...g_{n1}(x_n).
$$

We can now lift $\sigma$ to the path on $X_g$ given by  $\gamma(t)=(\sigma(t), g_{12}(x_1)...g_{(i-1)i}(x_{i-1}))$, for $t\in [t_{i-1},t_i)$, which joins $\gamma(0)=(x_0,1_G)$ with $\gamma(1)=(x_0,g_{12}(x_1)...g_{n1}(x_{n}))=(x_0,h)$.

If $1_G=f_g([\sigma])$ for some $\sigma$, as above we can lift $\sigma$ to some path $\gamma$ on $X_g$ joining $(x_0,1_G)$ with itself. Therefore, $\gamma$ is a loop on $X_g$. If the path component of $X_g$ containing $\gamma$ is simply connected, then $\gamma$ is nullhomotopic and so its $\sigma=p \circ \gamma$. This implies that $f_g$ is injective. 

On the other hand, choose a loop $\gamma$ in $X_g$ based in $(x_0,g)$. As above, $p\circ \gamma$ is a loop based in $x_0$ with $f_g([p\circ \gamma])=1_G$. If $f_g$ is injective then $p\circ \gamma$ is nullhomotopic. In a similar way to how we lifted $\sigma$ above, we can lift this homotopy to $X_g$ to obtain that $\gamma$ is nullhomotopic.

Putting these two together, $X_g$ is simply connected if and only if $f_g$ is a group isomorphism. In other words, $G$ is isomorphic to the fundamental group of $X$. 

This fact can be used to compute the fundamental group of the circle $S^1$. We can define the cover of $S^1=\{e^{it}: t\in [0,2\pi]\}$ given by $U=(e^{-i\epsilon},e^{i(\pi+\epsilon)})$ and $V=(e^{i(\pi-\epsilon)},e^{i\epsilon})$, for some small $\epsilon$, and the $\mathbb{Z}$-covering given by $g_{VU}(1)=1$ and $g_{UV}(-1)=0$. The topological space associated to this covering is

$$
(U \times \mathbb{Z} \sqcup V \times \mathbb{Z}) / \sim
$$

with the relation $(x,n) \sim (x,n+1)$, for $x \in (e^{-i\epsilon},e^{i\epsilon})$. This space is clearly homeomorphic to $\mathbb{R}$, which is simply connected. Therefore, $\pi_1(S^1)$ is isomorphic to $\mathbb{Z}$.

When $X$ is path-connected, locally path-connected and semilocally simply connected, we can find a cover $\mathfrak{U}$ such that any $f:\pi_1(X,x_0) \rightarrow G$ induces a $G$-covering based on $\mathfrak{U}$. In particular, the identity isomorphism $\mathrm{id}:\pi_1(X,x_0) \rightarrow \pi_1(X,x_0)$ induces a $G$-covering whose associated topological space is simply connected. This is called the *universal covering space*.

### The Galois theory of coverings

Let $X$ be a path-connected, locally path-connected and semilocally simply connected topological space and choose an open cover $\mathfrak{U}$ of $X$ satisfying properties P1 and P2. Fix once and for all a base point $x_0 \in X$.

**Definition**. A *regular* or *Galois covering space* is a pair $(Y,p)$, where $Y$ is a connected topological space and $p:Y\rightarrow X$ a continuous surjective map such that there is some group $G$ and some $\mathfrak{U}$-based $G$-covering $g$ with $Y=X_g$ and $p:X_g\rightarrow X$. We call $G$ the *Galois group* of $(Y,p)$.

Now we can prove the **Galois theorem of covering spaces**:

**Theorem**.  There is a one-to-one correspondence between the normal subgroups of the fundamental group $\pi_1(X,x_0)$ and the Galois coverings of $X$.

Consider $Y$ a Galois covering with Galois group $G$ and $g$ some $\mathfrak{U}$-based $G$-covering such that $Y=X_g$. Then we can associate to it the kernel of the monodromy representation $f_g:\pi_1(X,x_0) \rightarrow G$, which is a normal subgroup of $\pi_1(X,x_0)$. A different $g$ would yield another homomorphism, so the map is injective.

On the other hand, if $N$ is a normal subgroup of $\pi_1(X,x_0)$, associated to the natural projection $p:\pi_1(X,x_0) \rightarrow \pi_1(X,x_0)/N$ we have a $\mathfrak{U}$-based $\pi_1(X,x_0)/N$-covering $g$, whose associated topological space $X_g$ is a Galois covering of $X$. This construction is an inverse of the previous one. Indeed, by the isomorphism theorem and the universal property of the quotient there is a canonical isomorphism $\varphi:\pi_1(X,x_0)/\ker f_g \rightarrow G$ with $f_g= \varphi \circ p$.



------

[Take me to the blog index](https://guillegran.github.io/blog/indice.html)

[Take me home](https://guillegran.github.io)

